name: Sync master to gh-pages

on:
  push:
    branches:
      - master

jobs:
  merge-master-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Checkout gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages

    - name: Merge master into gh-pages
      run: |
        git merge origin/master

    - name: Push changes to gh-pages
      run: |
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
